spring:
  profiles:
    active: 
      -dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-huangliutan-dev
    
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-huangliutan-test